---
title: "Lab 1"
output: 
  html_document:
    fig_caption: yes
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: 
      collapsed: true
---

### 1. Software Installation

#### 1.1 R and RStudio

R is the based app to process R programming language, and RStudio integrates with R to provide further functionality such as graphical user interface (GUI). We need to install both **R** and **RStudio** for this workshop. \

**Note**: there are R and RStudio installed in the computer lab. Please use the PCs in the lab if you cannot install. \


#### 1.2 Install R
We will install R first.  \

Windows users: 

* Please go to the website: https://cran.rstudio.com/
* Download and install R
* Download R for Windows
* install R for the first time
* Download R-4.4.1 for Windows (Remember the folder where you save it!!)
* Go to the folder where you save the file “R-4.4.1-win.exe”, double click to run the installation, use default settings, click “Next” until the end 
* Finish


Mac users: 

* Please go to the website: https://cran.rstudio.com/
* Download R for macOS 
* Under the “Latest release”, download the version that is suitable for your machine (“R-4.4.1-arm64.pkg” or “R-4.4.1-x86_64.pkg”) --> save 
* Go to the folder where you save the file, run the installation, use default settings, click “Next” until the end
* Finish


#### 1.3 Install RStudio
Next, we will install RStudio, the GUI of R.  \

Windows users: 

* Please go to: https://posit.co/download/rstudio-desktop/ 
* Download RStudio desktop for windows, then Save
* Go to the folder where you download the file “RStudio-2024.04.2-764.exe” 
* Run the installation, use default settings, click “Next” until the end  
* Finish


Mac users:  

* Please go to: https://posit.co/download/rstudio-desktop/ 
* Scroll down 
* look for “macOS 12+”, click “RStudio-2024.04.2-764.dmg” and save
* Go to the folder where you download the file 
* Run the installation, use default settings, click “Next” until the end 
* Finish


