---
title: "Chapter 3: The Data Analysis & Visualization Workflow"
output: 
  html_document:
    fig_caption: yes
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: 
      collapsed: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{css style settings, echo = FALSE}
blockquote {
    padding: 10px 20px;
    margin: 0 0 20px;
    font-size: 15px;
    border-left: 5px solid #90e0ef;
}
```


### 3.1 Lab Goals 

This chapter aims to introduce the complete workflow of data analysis and visualization using R. After reading it, you should be able to:

* **import** data from local files 
* **clean** and **transforming** data, such as: 
  + extract data corpus 
  + join and merge data frames 
  + understand sorting and ordering 
* **draw** standard plots including:
  + histograms
  + bar charts 
  + line plots
  + scatter plots 
* **export** plots in different formats and know the differences between different formats 

### 3.2 Good Practice 

Okay, I guess you already know what I am going to repeat. However, there are something [new]{.ul} for this lab. 
Anyway, I will try to be brief :) 


#### 3.3 Organizing Folders

Similar to what we have done in previous labs, under the course folder, please create a folder called **lab 3**. Next, in the **lab 3** folder, please create two sub-folders that one is  **data** and another one is **plot**. 


