---
title: "Chapter 6: Map Making (3) Timeseries, Cartogram & Bivariate Visualization"
output: 
  html_document:
    fig_caption: yes
    theme: cosmo
    toc: yes
    toc_depth: 5
    toc_float: 
      collapsed: true
css: website.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 6.1 Lab Goals

[Chapter 4](https://fuzhen-yin.github.io/uccs_geoviz/lab4.html) and [Chapter 5](https://fuzhen-yin.github.io/uccs_geoviz/lab5.html) have introduced the fundamentals of spatial data manipulation and map-making, particularly, producing single-variable thematic maps. In this chapter, we will learn to: 

* visualize **time series** data
* create **cartograms**
* make **bivariate** choropleth map



### 6.2 Good Practice

#### 6.2.1 Organizing Folders & Sub-folders
Under the course folder, please create a folder called "**lab6**". Next, in the **lab6** folder, please create two [sub-folders]{.ul} that one is called "**data**" and another one is "**plot**". 

#### 6.2.2 Data
In this lab, we will explore data sources other than [US Census Bureau](https://data.census.gov/). Particularly, we will play with [Airbnb data](https://insideairbnb.com/get-the-data/) for the city of Denver (CO). 

> [AirBnb](https://insideairbnb.com/get-the-data/) has published datasets related to [listings]{.ul}, [reviews]{.ul}, and [neighborhoods]{.ul} in major cities or tourist destinations all over the world. [Here](https://docs.google.com/spreadsheets/d/1iWCNJcSutYqpULSQHlNyGInUvHg2BoUGoNRIGa6Szc4/edit?gid=1322284596#gid=1322284596) you can find the data dictionary of [Airbnb data](https://insideairbnb.com/get-the-data/). 



Please follow the steps below to [download]{.ul} data, [unzip]{.ul} it and [move]{.ul} the data to the required folder. 

* **Go** to https://github.com/fuzhen-yin/uccs_geoviz/blob/main/data/lab5_data.zip
* **Download** the file _"lab5_data.zip"_
* **Unzip** folder _"lab5_data.zip"_
* **Move** all files from the "_lab5_data_" folder to the _"data"_ folder under "_lab5_" see [Step 5.2.1](https://fuzhen-yin.github.io/uccs_geoviz/lab5.html#521_Organizing_Folders__Sub-folders) 


If there you have any questions about the above-mentioned steps, please refer to [Chapter 3.2.3](https://fuzhen-yin.github.io/uccs_geoviz/lab3.html#322_Data) for detailed instructions. 


#### 5.2.3 Launching R Studio

Again, we would like to start a **new project** from scratch with a **clean R Script**. Please do the following steps. If you have any questions about these steps, please refer to the relevant chapters for help. 

* Step 1: Make sure all existing R projects are **properly closed**. 
    + If *not*, please close it by going to *File* --> *Close Project* --> *Save* changes (see [Chapter 2.5](https://fuzhen-yin.github.io/uccs_geoviz/lab2.html#25_Close__Exit)). 
* Step 2: Create a **New Project** using **Existing Directory**, navigate to **lab5**, click **open**, then **Create Project**. (see [Chapter 1.3](https://fuzhen-yin.github.io/uccs_geoviz/lab1.html#13_Launching_RStudio)). 
* Step 3: Create a **New Script** by go to **File** --> **New File** --> **R Script**. **Save** the script by giving it a proper name.


#### 5.2.4 Before Start 

:::: {.greenbox data-latex=""}
::: {.left data-latex=""}
[**Heads-Up! **]{.ul}
:::

All scripts is **non-copyable**. Here are some **coding standards** and **best practices** to follow: 

* Use **comments** to explain code (try to annotate the codes by yourself). 
* Ensure there is sufficient **whitespace between lines** of text to improve legibility. 
* **Consistent** variable naming
* When naming a new column, creating a new folder or file, please:
    + **Avoid special characters** such as ", * _ = & " .
    + **Avoid adding blank spaces**. For example, instead of using a name as "plot 1" (x), please use "plot_1" (✓). 

::::