---
title: "Chapter 9: Mapping Point PatternS"
output: 
  html_document:
    fig_caption: yes
    theme: cosmo
    toc: yes
    toc_depth: 5
    toc_float: 
      collapsed: true
css: website.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### 9.1 Lab Goals

This chapter explores mapping of point patterns:

* Crating **grids** covering study area 
* **Point pattern** visualization 
* **Kernel Density Estimation** Mapping


### 9.2 Good Practice

#### 9.2.1 Organizing Folders & Sub-folders
Under the course folder, please create a folder called "**lab9**". Next, in the **lab9** folder, please create two [sub-folders]{.ul} that one is called "**data**" and another one is "**plot**". 

#### 9.2.2 Data
This chapter uses:

* [Crash data](https://policedata.coloradosprings.gov/Traffic-Crashes/Crash-Data/bjpt-tkzq/about_data) reported to CSPD in 2024.
* 2023 [Tiger Line Road Data](https://www.census.gov/cgi-bin/geo/shapefiles/index.php?year=2023&layergroup=Roads) from US Census Bureau
* 2023 Cartographic Boundary [County Subdivision](https://www.census.gov/geographies/mapping-files/time-series/geo/cartographic-boundary.html) from US Census Bureau


Download the lab's data: 

* **Go** to https://github.com/fuzhen-yin/uccs_geoviz/blob/main/data/lab9_data.zip
* **Download** the file _"lab9_data.zip"_
* **Unzip** folder _"lab9_data.zip"_
* **Move** all files from the "_lab9_data_" folder to the _"data"_ folder under "_lab9_" see [Step 9.2.1](https://fuzhen-yin.github.io/uccs_geoviz/lab9.html#821_Organizing_Folders__Sub-folders) 


If there you have any questions about the above-mentioned steps, please refer to [Chapter 3.2.3](https://fuzhen-yin.github.io/uccs_geoviz/lab3.html#322_Data) for detailed instructions. 


#### 9.2.3 Launching R Studio

Again, we would like to start a **new project** from scratch with a **clean R Script**. Please do the following steps. If you have any questions about these steps, please refer to the relevant chapters for help. 

* Step 1: Make sure all existing R projects are **properly closed**. 
    + If *not*, please close it by going to *File* --> *Close Project* --> *Save* changes (see [Chapter 2.5](https://fuzhen-yin.github.io/uccs_geoviz/lab2.html#25_Close__Exit)). 
* Step 2: Create a **New Project** using **Existing Directory**, navigate to **lab8**, click **open**, then **Create Project**. (see [Chapter 1.3](https://fuzhen-yin.github.io/uccs_geoviz/lab1.html#13_Launching_RStudio)). 
* Step 3: Create a **New Script** by go to **File** --> **New File** --> **R Script**. **Save** the script by giving it a proper name.










